[build]
  publish = "public"
  functions = "netlify/functions"

# Toutes les routes /api/* sont redirigées vers les fonctions serverless
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
